# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_game.ui'
#
# Created: Sun Jun 30 01:02:51 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NewGameDialog(object):
    def setupUi(self, NewGameDialog):
        NewGameDialog.setObjectName("NewGameDialog")
        NewGameDialog.resize(399, 272)
        self.gridLayout = QtGui.QGridLayout(NewGameDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtGui.QGroupBox(NewGameDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vsComputerRadio = QtGui.QRadioButton(self.groupBox_2)
        self.vsComputerRadio.setChecked(True)
        self.vsComputerRadio.setObjectName("vsComputerRadio")
        self.verticalLayout.addWidget(self.vsComputerRadio)
        self.vsPlayerRadio = QtGui.QRadioButton(self.groupBox_2)
        self.vsPlayerRadio.setObjectName("vsPlayerRadio")
        self.verticalLayout.addWidget(self.vsPlayerRadio)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.firstToMoveGroup = QtGui.QGroupBox(NewGameDialog)
        self.firstToMoveGroup.setObjectName("firstToMoveGroup")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.firstToMoveGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.randomRadio = QtGui.QRadioButton(self.firstToMoveGroup)
        self.randomRadio.setChecked(True)
        self.randomRadio.setObjectName("randomRadio")
        self.verticalLayout_2.addWidget(self.randomRadio)
        self.computerRadio = QtGui.QRadioButton(self.firstToMoveGroup)
        self.computerRadio.setObjectName("computerRadio")
        self.verticalLayout_2.addWidget(self.computerRadio)
        self.playerRadio = QtGui.QRadioButton(self.firstToMoveGroup)
        self.playerRadio.setObjectName("playerRadio")
        self.verticalLayout_2.addWidget(self.playerRadio)
        self.gridLayout.addWidget(self.firstToMoveGroup, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(NewGameDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.depthGroup = QtGui.QGroupBox(NewGameDialog)
        self.depthGroup.setObjectName("depthGroup")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.depthGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.depthGroup)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.depthSlider = QtGui.QSlider(self.depthGroup)
        self.depthSlider.setMinimum(2)
        self.depthSlider.setMaximum(9)
        self.depthSlider.setProperty("value", 5)
        self.depthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.depthSlider.setObjectName("depthSlider")
        self.horizontalLayout_2.addWidget(self.depthSlider)
        self.label_4 = QtGui.QLabel(self.depthGroup)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(-1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.depthGroup)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(218, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.depthGroup)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.depthGroup, 1, 0, 1, 2)

        self.retranslateUi(NewGameDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NewGameDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NewGameDialog.reject)
        QtCore.QObject.connect(self.vsPlayerRadio, QtCore.SIGNAL("toggled(bool)"), self.firstToMoveGroup.setDisabled)
        QtCore.QObject.connect(self.vsPlayerRadio, QtCore.SIGNAL("toggled(bool)"), self.depthGroup.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(NewGameDialog)

    def retranslateUi(self, NewGameDialog):
        NewGameDialog.setWindowTitle(QtGui.QApplication.translate("NewGameDialog", "New Game", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("NewGameDialog", "Players:", None, QtGui.QApplication.UnicodeUTF8))
        self.vsComputerRadio.setText(QtGui.QApplication.translate("NewGameDialog", "Computer vs. Player", None, QtGui.QApplication.UnicodeUTF8))
        self.vsPlayerRadio.setText(QtGui.QApplication.translate("NewGameDialog", "Player vs. Player", None, QtGui.QApplication.UnicodeUTF8))
        self.firstToMoveGroup.setTitle(QtGui.QApplication.translate("NewGameDialog", "First to Move:", None, QtGui.QApplication.UnicodeUTF8))
        self.randomRadio.setText(QtGui.QApplication.translate("NewGameDialog", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.computerRadio.setText(QtGui.QApplication.translate("NewGameDialog", "Computer", None, QtGui.QApplication.UnicodeUTF8))
        self.playerRadio.setText(QtGui.QApplication.translate("NewGameDialog", "Player", None, QtGui.QApplication.UnicodeUTF8))
        self.depthGroup.setTitle(QtGui.QApplication.translate("NewGameDialog", "Computer Search Depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewGameDialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NewGameDialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewGameDialog", "Easy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NewGameDialog", "Hard", None, QtGui.QApplication.UnicodeUTF8))

